logging:
  level:
    org:
      apache:
        kafka: OFF
    web: DEBUG

server:
  port: 8080

spring:
  kafka:
    bootstrap-servers: ${KAFKA_BROKER:localhost:9092}
    consumer:
      group-id: orchestrator-group
      auto-offset-reset: latest
    topic:
      start-saga: start-saga
      orchestrator: orchestrator
      finish-fail: finish-fail
      finish-success: finish-success