logging:
  level:
    web: DEBUG

server:
  port: 3000

spring:
  data:
    mongodb:
      database: admin
      uri: ${MONGO_DB_URI:mongodb://mongo:mongo@localhost:27017}
  devtools:
    livereload:
      enabled: true
      port: 33000