logging:
  level:
    org:
      apache:
        kafka: OFF
    web: DEBUG

server:
  port: 8092

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5434}/${DB_NAME:inventory-db}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
  devtools:
    livereload:
      enabled: true
      port: 38092
  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    show-sql: true
  kafka:
    bootstrap-servers: ${KAFKA_BROKER:localhost:9092}
    consumer:
      group-id: inventory-group
      auto-offset-reset: latest
    topic:
      inventory-fail: inventory-fail
      inventory-success: inventory-success
      orchestrator: orchestrator
